### ISSUE TITLE
Something wrong with sensitivity adjustments

### ISSUE THREAD

**Issue by elopio** [adafruit/Adafruit_L3GD20_U#11]
From https://github.com/adafruit/Adafruit_L3GD20_U/blob/master/Adafruit_L3GD20_U.h#L36

#define GYRO_SENSITIVITY_250DPS  (0.00875F)    // Roughly 22/256 for fixed point match
#define GYRO_SENSITIVITY_500DPS  (0.0175F)     // Roughly 45/256
#define GYRO_SENSITIVITY_2000DPS (0.070F) // Roughly 18/256

But the math doesn't seem correct:
22/256 = 0,0859375
45/256 = 0,17578125
18/256 = 0,0703125

Only the last one is correct.

**Comment by ladyada** [comment]
yah its not exact but we're following the datasheet:
https://www.pololu.com/file/0J563/L3GD20.pdf
see "Sensitivity" under section 2.1

**Comment by microbuilder** [comment]
Those fixed point values in the comments can be ignored since they aren't used anywhere ... it's a distraction from some earlier test code. Yes in theory the first two values are off, but the only values ever used are the floating point DPS coefficients. There is no fixed point math in this library:

```
  /* Compensate values depending on the resolution */
  switch(_range)
  {
    case GYRO_RANGE_250DPS:
      event->gyro.x *= GYRO_SENSITIVITY_250DPS;
      event->gyro.y *= GYRO_SENSITIVITY_250DPS;
      event->gyro.z *= GYRO_SENSITIVITY_250DPS;
      break;
    case GYRO_RANGE_500DPS:
      event->gyro.x *= GYRO_SENSITIVITY_500DPS;
      event->gyro.y *= GYRO_SENSITIVITY_500DPS;
      event->gyro.z *= GYRO_SENSITIVITY_500DPS;
      break;
    case GYRO_RANGE_2000DPS:
      event->gyro.x *= GYRO_SENSITIVITY_2000DPS;
      event->gyro.y *= GYRO_SENSITIVITY_2000DPS;
      event->gyro.z *= GYRO_SENSITIVITY_2000DPS;
      break;
  }
```

**Comment by elopio** [comment]
Thanks for the info! It's great to find where the values come from.
