### ISSUE TITLE
Wire.requestFrom() should not be followed by Wire.endTransmission().

### ISSUE THREAD

**Issue by Koepel** [adafruit/Adafruit_L3GD20_U#14]
In the file "Adafruit_L3GD20_U.cpp", there is a `Wire.endTransmission()` after a `Wire.requestFrom()`. Those `Wire.endTransmission()` may be removed. They are at the moment at line 81 and 650.
Explanation: [Common-mistakes#2](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#2)

**Comment by microbuilder** [comment]
Fixed via https://github.com/adafruit/Adafruit_L3GD20_U/commit/0354f48af0e8f4bccc8fd811a43212dc9805e26b
