### ISSUE TITLE
No need to wait for Wire.available().

### ISSUE THREAD

**Issue by Koepel** [adafruit/Adafruit_L3GD20_U#7]
After Wire.requestFrom() it is not correct to wait for data. That is used twice in the code.
When the Wire.requestFrom() returns, the I2C transmission has completely finished, and the received data is in the buffer.

**Comment by microbuilder** [comment]
Fixed in https://github.com/adafruit/Adafruit_L3GD20_U/commit/7eee228ff2d235a04a2ebe343969ac8cbd712c11
