### ISSUE TITLE
Adafruit_L3GD20_Unified::begin() blocks forever if no chip is connected

### ISSUE THREAD

**Issue by christianVT** [adafruit/Adafruit_L3GD20_U#8]

**Comment by mantielero** [comment]
I have exactly the same issue. Does anybody how to fix it?

**Comment by mantielero** [comment]
The library L3G seem to work fine with the sensor.

**Comment by microbuilder** [comment]
The blocking behaviour is due to the 'while(1)' here which will stall forever. Simply remove that line to continue, though the example won't be very useful anymore. :P 

```
  /* Initialise the sensor */
  if(!gyro.begin())
  {
    /* There was a problem detecting the L3GD20 ... check your connections */
    Serial.println("Ooops, no L3GD20 detected ... Check your wiring!");
    while(1);
  }
```
